// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHYf9hFGeiWmmuc_eKXAqhG7Fp7k7-omg',
    appId: '1:697080221333:android:5c0a29460e5d11bf9c159c',
    messagingSenderId: '697080221333',
    projectId: 'scholars-gyan',
    storageBucket: 'scholars-gyan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_8M-PPWUUNGrvFpqv6-sxXcioK2__Oxo',
    appId: '1:697080221333:ios:d74d35322f47be369c159c',
    messagingSenderId: '697080221333',
    projectId: 'scholars-gyan',
    storageBucket: 'scholars-gyan.firebasestorage.app',
    androidClientId: '697080221333-cnpvp3fta52d4o1degurted2ijdlgo78.apps.googleusercontent.com',
    iosClientId: '697080221333-939tn0g2iduh35447hqhi4ucjc6vir2p.apps.googleusercontent.com',
    iosBundleId: 'com.itwlabs.scholargyan',
  );

}